// Generated by https://quicktype.io

export interface BreedsByFDA {
    meta:    Meta;
    results: Result[];
}

export interface Meta {
    disclaimer:   string;
    terms:        string;
    license:      string;
    last_updated: string;
}

export interface Result {
    term:  string;
    count: number;
}
